FROM golang:1.24.4-bookworm AS build

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o app ./cmd/web

FROM debian:bookworm-slim

WORKDIR /app

COPY --from=build /app/app .

RUN apt-get update && \
    apt-get install -y --no-install-recommends ca-certificates curl && \
    rm -rf /var/lib/apt/lists/*

CMD ["./app"]